# Generated by Django 3.1.4 on 2021-05-22 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
