# Generated by Django 3.1.4 on 2021-05-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='product_image2',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image1',
            field=models.ImageField(default='', upload_to='productimg'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
