# Generated by Django 3.1.4 on 2021-05-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210526_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image1',
            new_name='product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image2',
        ),
    ]
