# Generated by Django 3.1.4 on 2021-05-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210526_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image1',
            field=models.ImageField(default='', upload_to='productimg'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(default='', upload_to='productimg'),
        ),
    ]
