# Generated by Django 3.1.4 on 2021-05-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210526_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('S', 'Shoes'), ('SH', 'Shades')], max_length=2),
        ),
    ]
